CREATE TABLE classes (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  section VARCHAR NOT NULL,
  teacher_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);

CREATE TABLE students (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  roll VARCHAR NOT NULL,
  father_name VARCHAR NOT NULL,
  mobile_no VARCHAR NOT NULL,
  class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT (now())
);
