// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package db

import (
	"context"
	"time"
)

const createAttendance = `-- name: CreateAttendance :one
INSERT INTO attendance (
  student_id,
  date,
  status
) VALUES (
  $1, $2, $3
) RETURNING id, student_id, date, status, created_at
`

type CreateAttendanceParams struct {
	StudentID int64     `json:"student_id"`
	Date      time.Time `json:"date"`
	Status    string    `json:"status"`
}

func (q *Queries) CreateAttendance(ctx context.Context, arg CreateAttendanceParams) (Attendance, error) {
	row := q.db.QueryRowContext(ctx, createAttendance, arg.StudentID, arg.Date, arg.Status)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Date,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAttendanceByDate = `-- name: GetAttendanceByDate :many
SELECT a.id, a.student_id, a.date, a.status, a.created_at, s.name as student_name, s.roll
FROM attendance a
JOIN students s ON a.student_id = s.id
WHERE s.class_id = $1 AND a.date = $2
`

type GetAttendanceByDateParams struct {
	ClassID int64     `json:"class_id"`
	Date    time.Time `json:"date"`
}

type GetAttendanceByDateRow struct {
	ID          int64     `json:"id"`
	StudentID   int64     `json:"student_id"`
	Date        time.Time `json:"date"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	StudentName string    `json:"student_name"`
	Roll        string    `json:"roll"`
}

func (q *Queries) GetAttendanceByDate(ctx context.Context, arg GetAttendanceByDateParams) ([]GetAttendanceByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttendanceByDate, arg.ClassID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceByDateRow
	for rows.Next() {
		var i GetAttendanceByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.StudentName,
			&i.Roll,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceReport = `-- name: GetAttendanceReport :many
SELECT a.id, a.student_id, a.date, a.status, a.created_at, s.name as student_name, s.roll
FROM attendance a
JOIN students s ON a.student_id = s.id
WHERE s.class_id = $1 AND a.date BETWEEN $2 AND $3
`

type GetAttendanceReportParams struct {
	ClassID int64     `json:"class_id"`
	Date    time.Time `json:"date"`
	Date_2  time.Time `json:"date_2"`
}

type GetAttendanceReportRow struct {
	ID          int64     `json:"id"`
	StudentID   int64     `json:"student_id"`
	Date        time.Time `json:"date"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	StudentName string    `json:"student_name"`
	Roll        string    `json:"roll"`
}

func (q *Queries) GetAttendanceReport(ctx context.Context, arg GetAttendanceReportParams) ([]GetAttendanceReportRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttendanceReport, arg.ClassID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceReportRow
	for rows.Next() {
		var i GetAttendanceReportRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.StudentName,
			&i.Roll,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttendance = `-- name: UpsertAttendance :one
INSERT INTO attendance (student_id, date, status)
VALUES ($1, $2, $3)
ON CONFLICT (student_id, date)
DO UPDATE SET status = $3
RETURNING id, student_id, date, status, created_at
`

type UpsertAttendanceParams struct {
	StudentID int64     `json:"student_id"`
	Date      time.Time `json:"date"`
	Status    string    `json:"status"`
}

func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (Attendance, error) {
	row := q.db.QueryRowContext(ctx, upsertAttendance, arg.StudentID, arg.Date, arg.Status)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Date,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTeacherDailyAttendanceStats = `-- name: GetTeacherDailyAttendanceStats :one
SELECT
    COUNT(*) FILTER (WHERE a.status = 'present') as present_count,
    COUNT(*) as total_count
FROM attendance a
JOIN students s ON a.student_id = s.id
JOIN classes c ON s.class_id = c.id
WHERE c.teacher_id = $1 AND a.date = $2
`

type GetTeacherDailyAttendanceStatsParams struct {
	TeacherID int64     `json:"teacher_id"`
	Date      time.Time `json:"date"`
}

type GetTeacherDailyAttendanceStatsRow struct {
	PresentCount int64 `json:"present_count"`
	TotalCount   int64 `json:"total_count"`
}

func (q *Queries) GetTeacherDailyAttendanceStats(ctx context.Context, arg GetTeacherDailyAttendanceStatsParams) (GetTeacherDailyAttendanceStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTeacherDailyAttendanceStats, arg.TeacherID, arg.Date)
	var i GetTeacherDailyAttendanceStatsRow
	err := row.Scan(&i.PresentCount, &i.TotalCount)
	return i, err
}
