// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: class.sql

package db

import (
	"context"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes (
  name,
  section,
  teacher_id
) VALUES (
  $1, $2, $3
) RETURNING id, name, section, teacher_id, created_at
`

type CreateClassParams struct {
	Name      string `json:"name"`
	Section   string `json:"section"`
	TeacherID int64  `json:"teacher_id"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass, arg.Name, arg.Section, arg.TeacherID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Section,
		&i.TeacherID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM classes
WHERE id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteClass, id)
	return err
}

const getClass = `-- name: GetClass :one
SELECT id, name, section, teacher_id, created_at FROM classes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClass(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRowContext(ctx, getClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Section,
		&i.TeacherID,
		&i.CreatedAt,
	)
	return i, err
}

const listClasses = `-- name: ListClasses :many
SELECT id, name, section, teacher_id, created_at FROM classes
WHERE teacher_id = $1
ORDER BY id
`

func (q *Queries) ListClasses(ctx context.Context, teacherID int64) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, listClasses, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Section,
			&i.TeacherID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE classes
SET name = $2, section = $3
WHERE id = $1
RETURNING id, name, section, teacher_id, created_at
`

type UpdateClassParams struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Section string `json:"section"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, updateClass, arg.ID, arg.Name, arg.Section)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Section,
		&i.TeacherID,
		&i.CreatedAt,
	)
	return i, err
}
