// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exam.sql

package db

import (
	"context"
	"time"
)

const createExam = `-- name: CreateExam :one
INSERT INTO exams (
  class_id,
  name,
  total_marks
) VALUES (
  $1, $2, $3
) RETURNING id, class_id, name, total_marks, created_at
`

type CreateExamParams struct {
	ClassID    int64  `json:"class_id"`
	Name       string `json:"name"`
	TotalMarks int32  `json:"total_marks"`
}

func (q *Queries) CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error) {
	row := q.db.QueryRowContext(ctx, createExam, arg.ClassID, arg.Name, arg.TotalMarks)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.Name,
		&i.TotalMarks,
		&i.CreatedAt,
	)
	return i, err
}

const getResultsByExam = `-- name: GetResultsByExam :many
SELECT r.id, r.exam_id, r.student_id, r.obtained_marks, r.created_at, s.name as student_name, s.roll
FROM results r
JOIN students s ON r.student_id = s.id
WHERE r.exam_id = $1
ORDER BY s.roll
`

type GetResultsByExamRow struct {
	ID            int64     `json:"id"`
	ExamID        int64     `json:"exam_id"`
	StudentID     int64     `json:"student_id"`
	ObtainedMarks int32     `json:"obtained_marks"`
	CreatedAt     time.Time `json:"created_at"`
	StudentName   string    `json:"student_name"`
	Roll          string    `json:"roll"`
}

func (q *Queries) GetResultsByExam(ctx context.Context, examID int64) ([]GetResultsByExamRow, error) {
	rows, err := q.db.QueryContext(ctx, getResultsByExam, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResultsByExamRow
	for rows.Next() {
		var i GetResultsByExamRow
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.StudentID,
			&i.ObtainedMarks,
			&i.CreatedAt,
			&i.StudentName,
			&i.Roll,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExams = `-- name: ListExams :many
SELECT id, class_id, name, total_marks, created_at FROM exams
WHERE class_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListExams(ctx context.Context, classID int64) ([]Exam, error) {
	rows, err := q.db.QueryContext(ctx, listExams, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.Name,
			&i.TotalMarks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertResult = `-- name: UpsertResult :one
INSERT INTO results (
  exam_id,
  student_id,
  obtained_marks
) VALUES (
  $1, $2, $3
)
ON CONFLICT (exam_id, student_id)
DO UPDATE SET obtained_marks = $3
RETURNING id, exam_id, student_id, obtained_marks, created_at
`

type UpsertResultParams struct {
	ExamID        int64 `json:"exam_id"`
	StudentID     int64 `json:"student_id"`
	ObtainedMarks int32 `json:"obtained_marks"`
}

func (q *Queries) UpsertResult(ctx context.Context, arg UpsertResultParams) (Result, error) {
	row := q.db.QueryRowContext(ctx, upsertResult, arg.ExamID, arg.StudentID, arg.ObtainedMarks)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.StudentID,
		&i.ObtainedMarks,
		&i.CreatedAt,
	)
	return i, err
}
