// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Attendance struct {
	ID        int64     `json:"id"`
	StudentID int64     `json:"student_id"`
	Date      time.Time `json:"date"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type Class struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Section   string    `json:"section"`
	TeacherID int64     `json:"teacher_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Exam struct {
	ID         int64     `json:"id"`
	ClassID    int64     `json:"class_id"`
	Name       string    `json:"name"`
	TotalMarks int32     `json:"total_marks"`
	CreatedAt  time.Time `json:"created_at"`
}

type LessonPlan struct {
	ID        int64          `json:"id"`
	ClassID   int64          `json:"class_id"`
	Date      time.Time      `json:"date"`
	Topic     string         `json:"topic"`
	Note      sql.NullString `json:"note"`
	CreatedAt time.Time      `json:"created_at"`
}

type Resource struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	FilePath  string    `json:"file_path"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

type Result struct {
	ID            int64     `json:"id"`
	ExamID        int64     `json:"exam_id"`
	StudentID     int64     `json:"student_id"`
	ObtainedMarks int32     `json:"obtained_marks"`
	CreatedAt     time.Time `json:"created_at"`
}

type Routine struct {
	ID          int64     `json:"id"`
	ClassID     int64     `json:"class_id"`
	DayOfWeek   string    `json:"day_of_week"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	Subject     string    `json:"subject"`
	TeacherName string    `json:"teacher_name"`
	CreatedAt   time.Time `json:"created_at"`
}

type Student struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Roll       string    `json:"roll"`
	FatherName string    `json:"father_name"`
	MobileNo   string    `json:"mobile_no"`
	ClassID    int64     `json:"class_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID         int64     `json:"id"`
	Phone      string    `json:"phone"`
	Password   string    `json:"password"`
	FullName   string    `json:"full_name"`
	SchoolName string    `json:"school_name"`
	CreatedAt  time.Time `json:"created_at"`
}
