// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource.sql

package db

import (
	"context"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
  title,
  file_path,
  type
) VALUES (
  $1, $2, $3
) RETURNING id, title, file_path, type, created_at
`

type CreateResourceParams struct {
	Title    string `json:"title"`
	FilePath string `json:"file_path"`
	Type     string `json:"type"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource, arg.Title, arg.FilePath, arg.Type)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, title, file_path, type, created_at FROM resources
ORDER BY created_at DESC
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
