// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routine.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createLessonPlan = `-- name: CreateLessonPlan :one
INSERT INTO lesson_plans (
  class_id,
  date,
  topic,
  note
) VALUES (
  $1, $2, $3, $4
) RETURNING id, class_id, date, topic, note, created_at
`

type CreateLessonPlanParams struct {
	ClassID int64          `json:"class_id"`
	Date    time.Time      `json:"date"`
	Topic   string         `json:"topic"`
	Note    sql.NullString `json:"note"`
}

func (q *Queries) CreateLessonPlan(ctx context.Context, arg CreateLessonPlanParams) (LessonPlan, error) {
	row := q.db.QueryRowContext(ctx, createLessonPlan,
		arg.ClassID,
		arg.Date,
		arg.Topic,
		arg.Note,
	)
	var i LessonPlan
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.Date,
		&i.Topic,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createRoutine = `-- name: CreateRoutine :one
INSERT INTO routines (
  class_id,
  day_of_week,
  start_time,
  end_time,
  subject,
  teacher_name
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, class_id, day_of_week, start_time, end_time, subject, teacher_name, created_at
`

type CreateRoutineParams struct {
	ClassID     int64     `json:"class_id"`
	DayOfWeek   string    `json:"day_of_week"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	Subject     string    `json:"subject"`
	TeacherName string    `json:"teacher_name"`
}

func (q *Queries) CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error) {
	row := q.db.QueryRowContext(ctx, createRoutine,
		arg.ClassID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Subject,
		arg.TeacherName,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Subject,
		&i.TeacherName,
		&i.CreatedAt,
	)
	return i, err
}

const listLessonPlans = `-- name: ListLessonPlans :many
SELECT id, class_id, date, topic, note, created_at FROM lesson_plans
WHERE class_id = $1
ORDER BY date DESC
`

func (q *Queries) ListLessonPlans(ctx context.Context, classID int64) ([]LessonPlan, error) {
	rows, err := q.db.QueryContext(ctx, listLessonPlans, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonPlan
	for rows.Next() {
		var i LessonPlan
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.Date,
			&i.Topic,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutinesByClass = `-- name: ListRoutinesByClass :many
SELECT id, class_id, day_of_week, start_time, end_time, subject, teacher_name, created_at FROM routines
WHERE class_id = $1
ORDER BY
  CASE
    WHEN day_of_week = 'Sunday' THEN 1
    WHEN day_of_week = 'Monday' THEN 2
    WHEN day_of_week = 'Tuesday' THEN 3
    WHEN day_of_week = 'Wednesday' THEN 4
    WHEN day_of_week = 'Thursday' THEN 5
    WHEN day_of_week = 'Friday' THEN 6
    WHEN day_of_week = 'Saturday' THEN 7
  END,
  start_time
`

func (q *Queries) ListRoutinesByClass(ctx context.Context, classID int64) ([]Routine, error) {
	rows, err := q.db.QueryContext(ctx, listRoutinesByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Subject,
			&i.TeacherName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeacherDailyRoutinesCount = `-- name: GetTeacherDailyRoutinesCount :one
SELECT COUNT(*)
FROM routines r
JOIN classes c ON r.class_id = c.id
WHERE c.teacher_id = $1 AND r.day_of_week = $2
`

type GetTeacherDailyRoutinesCountParams struct {
	TeacherID int64  `json:"teacher_id"`
	DayOfWeek string `json:"day_of_week"`
}

func (q *Queries) GetTeacherDailyRoutinesCount(ctx context.Context, arg GetTeacherDailyRoutinesCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTeacherDailyRoutinesCount, arg.TeacherID, arg.DayOfWeek)
	var count int64
	err := row.Scan(&count)
	return count, err
}
