// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student.sql

package db

import (
	"context"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
  name,
  roll,
  father_name,
  mobile_no,
  class_id
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, roll, father_name, mobile_no, class_id, created_at
`

type CreateStudentParams struct {
	Name       string `json:"name"`
	Roll       string `json:"roll"`
	FatherName string `json:"father_name"`
	MobileNo   string `json:"mobile_no"`
	ClassID    int64  `json:"class_id"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, createStudent,
		arg.Name,
		arg.Roll,
		arg.FatherName,
		arg.MobileNo,
		arg.ClassID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Roll,
		&i.FatherName,
		&i.MobileNo,
		&i.ClassID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students
WHERE id = $1
`

func (q *Queries) DeleteStudent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStudent, id)
	return err
}

const getStudent = `-- name: GetStudent :one
SELECT id, name, roll, father_name, mobile_no, class_id, created_at FROM students
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStudent(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Roll,
		&i.FatherName,
		&i.MobileNo,
		&i.ClassID,
		&i.CreatedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, name, roll, father_name, mobile_no, class_id, created_at FROM students
WHERE class_id = $1
ORDER BY roll
`

func (q *Queries) ListStudents(ctx context.Context, classID int64) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listStudents, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Roll,
			&i.FatherName,
			&i.MobileNo,
			&i.ClassID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET name = $2, roll = $3, father_name = $4, mobile_no = $5
WHERE id = $1
RETURNING id, name, roll, father_name, mobile_no, class_id, created_at
`

type UpdateStudentParams struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Roll       string `json:"roll"`
	FatherName string `json:"father_name"`
	MobileNo   string `json:"mobile_no"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudent,
		arg.ID,
		arg.Name,
		arg.Roll,
		arg.FatherName,
		arg.MobileNo,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Roll,
		&i.FatherName,
		&i.MobileNo,
		&i.ClassID,
		&i.CreatedAt,
	)
	return i, err
}
