// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  phone,
  password,
  full_name,
  school_name
) VALUES (
  $1, $2, $3, $4
) RETURNING id, phone, password, full_name, school_name, created_at
`

type CreateUserParams struct {
	Phone      string `json:"phone"`
	Password   string `json:"password"`
	FullName   string `json:"full_name"`
	SchoolName string `json:"school_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Phone,
		arg.Password,
		arg.FullName,
		arg.SchoolName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Password,
		&i.FullName,
		&i.SchoolName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, password, full_name, school_name, created_at FROM users
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Password,
		&i.FullName,
		&i.SchoolName,
		&i.CreatedAt,
	)
	return i, err
}
